import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Form, Input } from "react-daisyui";
import { useForm } from "react-hook-form";
import { api } from "~/utils/api";

type RegisterForm = {
  name: string;
  contactInfo: string;
};

const Home: NextPage = () => {
  const createUser = api.users.createUser.useMutation();
  const router = useRouter();

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterForm>();

  const onSubmit = async (data: RegisterForm) => {
    // TODO: call that mutation method
    const _ = await createUser.mutateAsync(data);
    router.push("/waiting");
  };
  return (
    <>
      <Head>
        <title>Speed Date</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex h-screen flex-col items-center justify-center gap-6 p-4">
        <h3 className="text-xl">Join a Speed Dating Session</h3>
        <Form onSubmit={handleSubmit(onSubmit)} className="flex w-1/3 flex-col">
          <div>
            <Form.Label title="Name"></Form.Label>
            <Input
              {...register("name", { required: true })}
              className="w-full"
              type="text"
              placeholder="your display name"
              bordered
            />
            {errors.name && (
              <span className="text-red-500">The name is required</span>
            )}
          </div>
          <div className="h-4"></div>
          <div>
            <Form.Label title="Contact Info"></Form.Label>
            <Input
              {...register("contactInfo", { required: true })}
              className="w-full"
              type="text"
              placeholder="your fb link, phone, email, you're choice"
              bordered
            />
            {errors.contactInfo && (
              <span className="text-red-500">The contact info is required</span>
            )}
          </div>
          <div className="h-12"></div>
          <Button type="submit" color="primary">
            join session
          </Button>
        </Form>
      </main>
    </>
  );
};

export default Home;
