import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const WaitingPage: NextPage = () => {
  const { data } = api.users.findMatch.useQuery(userId);

  return (
    <>
      <Head>
        <title>Waiting for Users</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex h-screen flex-col items-center justify-center gap-6 p-4">
        <h3 className="text-xl">Waiting for Users to Connect with...</h3>
      </main>
    </>
  );
};

export default WaitingPage;
